# Generated by Django 4.2.5 on 2023-09-08 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssuntosRegistroLivros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assuntos_registros_livros', to='app.assunto')),
            ],
        ),
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50, null=True)),
                ('nome_do_meio', models.CharField(max_length=50, null=True)),
                ('ultimo_nome', models.CharField(max_length=50, null=True)),
                ('data_nascimento', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutoresRegistroLivros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autores_registros_livros', to='app.autores')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(default='', max_length=13, unique=True)),
                ('title', models.CharField(default='', max_length=255)),
                ('url', models.URLField(default=list)),
                ('authors', models.JSONField(default=list)),
                ('isbn_10', models.CharField(default='', max_length=10)),
                ('isbn_13', models.CharField(default='', max_length=13)),
                ('openlibrary_key', models.CharField(default='', max_length=255)),
                ('publishers', models.JSONField(default=list)),
                ('publish_date', models.CharField(default='', max_length=20)),
                ('notes', models.TextField(default=list)),
                ('cover_small', models.URLField(default=list)),
                ('cover_medium', models.URLField(default=list)),
                ('cover_large', models.URLField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamada', models.CharField(max_length=50, unique=True)),
                ('assunto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano_fundacao', models.DateField(null=True)),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('id_cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cidade')),
                ('id_tipos_de_usuarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLivros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ano_publicacao', models.IntegerField(null=True)),
                ('edicao', models.CharField(max_length=50, null=True)),
                ('isbn', models.CharField(max_length=20, null=True)),
                ('numero_paginas', models.IntegerField(null=True)),
                ('resumo', models.TextField(null=True)),
                ('notas', models.TextField(null=True)),
                ('assuntos_registro_livros', models.ManyToManyField(related_name='livros_assuntos', through='app.AssuntosRegistroLivros', to='app.assunto')),
                ('autores_registro_livros', models.ManyToManyField(related_name='livros_autores', through='app.AutoresRegistroLivros', to='app.autores')),
                ('id_chamada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.classificacao')),
                ('id_editora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.editora')),
                ('idioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='app.pais')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='app.estado'),
        ),
        migrations.AddField(
            model_name='autoresregistrolivros',
            name='registro_livros',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autores_registros_livros', to='app.registrolivros'),
        ),
        migrations.AddField(
            model_name='autores',
            name='id_cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cidade'),
        ),
        migrations.AddField(
            model_name='assuntosregistrolivros',
            name='registro_livros',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assuntos_registros_livros', to='app.registrolivros'),
        ),
    ]
