# Generated by Django 4.2.5 on 2023-09-08 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exemplar', models.IntegerField()),
                ('data_aquisicao', models.DateField(null=True)),
                ('preco', models.FloatField(null=True)),
                ('id_registro_livros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.registrolivros')),
                ('id_tipo_aquisicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipoaquisicao')),
            ],
        ),
    ]
