# Generated by Django 4.2.5 on 2023-09-10 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tipoaquisicao_tombo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('prazo_em_dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LimiteDeLivros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('tipo_de_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipodeemprestimo')),
            ],
        ),
    ]
