# Generated by Django 4.2.5 on 2023-09-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_usuario_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField()),
                ('id_tipos_de_emprestimos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipodeemprestimo')),
                ('id_tombo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tombo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
                ('status_emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.statusemprestimo')),
            ],
        ),
    ]
