# Generated by Django 4.2.5 on 2023-09-13 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipodeemprestimo',
            table='app_tipodeemprestimo',
        ),
    ]
