# Generated by Django 3.1.3 on 2023-08-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='json_data',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_large',
            field=models.URLField(default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_medium',
            field=models.URLField(default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_small',
            field=models.URLField(default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_10',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_13',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='openlibrary_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='publishers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default=list),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=13, unique=True),
        ),
    ]
