# Generated by Django 4.2.5 on 2023-09-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_limitedelivros_tipo_de_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
    ]
